# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_FjEs7KcTWIs0cuItiSsQB61V4IaFu0
"""

pip install copernicusmarine pandas numpy xgboost scikit-learn

import datetime
import os
import numpy as np
import pandas as pd

# Pustaka API Copernicus Marine (EU Marine Data Platform)
import copernicusmarine
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

# ==========================================
# 1. KONFIGURASI LOKASI PLTGU GRATI (PASURUAN)
# ==========================================
GRATI_LAT = -7.5950  # Lintang PLTGU Grati
GRATI_LON = 112.8943  # Bujur PLTGU Grati

# Bounding box presisi di sekitar intake PLTGU Grati (~5km radius)
LAT_MIN, LAT_MAX = GRATI_LAT - 0.04, GRATI_LAT + 0.04
LON_MIN, LON_MAX = GRATI_LON - 0.04, GRATI_LON + 0.04


# ==========================================
# 2. INGESTION DATA OSEANOGRAFI REAL-TIME (GRATI)
# ==========================================
def fetch_realtime_grati_ocean_data(lat_min, lat_max, lon_min, lon_max):
  """Mengambil data oseanografi fisik & biogeokimia real-time dari Copernicus API

  untuk area pesisir PLTGU Grati, Pasuruan.
  """
  today = datetime.datetime.now()
  start_date = (today - datetime.timedelta(days=2)).strftime('%Y-%m-%d')
  end_date = today.strftime('%Y-%m-%d')

  print(
      f'[*] Mengunduh data oseanografi PLTGU Grati ({start_date} s/d'
      f' {end_date})...'
  )

  try:
    # Fetch Data Fisik Laut (SST, Salinitas, Arus)
    ds_phys = copernicusmarine.open_dataset(
        dataset_id='cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m',
        minimum_latitude=lat_min,
        maximum_latitude=lat_max,
        minimum_longitude=lon_min,
        maximum_longitude=lon_max,
        start_datetime=start_date,
        end_datetime=end_date,
    )
    df_phys = ds_phys.to_dataframe().reset_index()

    # Hitung Kecepatan Arus Total (Magnitudo Vector Arus uo & vo)
    df_phys['current_speed'] = np.sqrt(df_phys['uo'] ** 2 + df_phys['vo'] ** 2)
    latest_phys = df_phys.mean(numeric_only=True)

    # Fetch Data Biogeokimia (Klorofil-a / Plankton)
    ds_bio = copernicusmarine.open_dataset(
        dataset_id='cmems_mod_glo_bgc-bio_anfc_0.25deg_P1D-m',
        minimum_latitude=lat_min,
        maximum_latitude=lat_max,
        minimum_longitude=lon_min,
        maximum_longitude=lon_max,
        start_datetime=start_date,
        end_datetime=end_date,
    )
    df_bio = ds_bio.to_dataframe().reset_index()
    latest_bio = df_bio.mean(numeric_only=True)

    return {
        'timestamp': today.strftime('%Y-%m-%d %H:%M:%S'),
        'sst': float(latest_phys.get('thetao', 29.8)),
        'salinity': float(latest_phys.get('so', 32.8)),
        'current_speed': float(latest_phys.get('current_speed', 0.30)),
        'chlorophyll_a': float(latest_bio.get('chl', 1.8)),
        'wind_speed': float(np.random.uniform(3.0, 9.0)),
    }

  except Exception as e:
    print(f'[!] Gagal mengunduh dari API ({e}). Menggunakan data simulasi...')
    # Dummy fallback data apabila API credentials belum dikonfigurasi
    return {
        'timestamp': today.strftime('%Y-%m-%d %H:%M:%S'),
        'sst': 30.1,  # Peningkatan suhu memicu blooming
        'salinity': 33.2,
        'current_speed': 0.42,
        'chlorophyll_a': 2.5,  # Tingkat klorofil-a tinggi
        'wind_speed': 7.2,
    }


# ==========================================
# 3. SYNTHETIC DATASET GENERATOR (Karakteristik Pesisir Grati)
# ==========================================
def generate_grati_training_data(n_samples=1200):
  """Membuat synthetic historical dataset berdasarkan karakteristik fisik perairan Grati.

  Perairan Grati dangkal & hangat (Selat Madura), sensitif terhadap blooming
  ubur-ubur.
  """
  np.random.seed(42)

  # Distribusi variabel laut khas Pasuruan / Selat Madura
  sst = np.random.normal(loc=29.5, scale=1.2, size=n_samples)
  salinity = np.random.normal(loc=32.5, scale=1.1, size=n_samples)
  current_speed = np.random.exponential(scale=0.25, size=n_samples)
  chlorophyll = np.random.gamma(shape=2.2, scale=0.7, size=n_samples)
  wind_speed = np.random.uniform(1.0, 12.0, size=n_samples)

  # Pembobotan indikator risiko blooming ubur-ubur di SWI Grati
  risk_score = (
      (sst - 28.5) * 0.35  # Pengaruh Suhu Air Laut
      + (chlorophyll) * 0.35  # Pengaruh Makanan (Plankton)
      + (current_speed) * 0.15  # Pengaruh Arus Laut
      + (wind_speed * 0.15)  # Pengaruh Angin Laut menuju Darat
  )

  # Kategori Label: 0 = Low Risk, 1 = Medium Risk, 2 = High Risk (Emergency)
  labels = pd.qcut(risk_score, q=3, labels=[0, 1, 2])

  return pd.DataFrame({
      'sst': sst,
      'salinity': salinity,
      'current_speed': current_speed,
      'chlorophyll_a': chlorophyll,
      'wind_speed': wind_speed,
      'risk_level': labels,
  })


# ==========================================
# 4. TRAINING MODEL ML (XGBoost)
# ==========================================
def train_grati_model():
  print('[*] Melatih model Machine Learning XGBoost untuk PLTGU Grati...')
  df_train = generate_grati_training_data(1500)

  X = df_train.drop(columns=['risk_level'])
  y = df_train['risk_level']

  X_train, X_test, y_train, y_test = train_test_split(
      X, y, test_size=0.2, random_state=42
  )

  model = XGBClassifier(
      n_estimators=120,
      learning_rate=0.04,
      max_depth=4,
      eval_metric='mlogloss',
  )
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  print('\n--- EVALUASI PERFORMA MODEL MONITORING GRATI ---')
  print(
      classification_report(
          y_test, y_pred, target_names=['Aman (Low)', 'Waspada (Med)', 'Bahaya (High)']
      )
  )

  return model


# ==========================================
# 5. EXECUTION & REALTIME MONITORING PIPELINE
# ==========================================
def run_grati_monitoring_system():
  print('===========================================================')
  print('  REAL-TIME JELLYFISH MONITORING SYSTEM - PLTGU GRATI')
  print('===========================================================')

  # 1. Melatih Model
  model = train_grati_model()

  # 2. Mengambil Data Real-Time di Koordinat Intake Grati
  realtime_data = fetch_realtime_grati_ocean_data(
      LAT_MIN, LAT_MAX, LON_MIN, LON_MAX
  )

  # 3. Format DataFrame Input
  features = pd.DataFrame([{
      'sst': realtime_data['sst'],
      'salinity': realtime_data['salinity'],
      'current_speed': realtime_data['current_speed'],
      'chlorophyll_a': realtime_data['chlorophyll_a'],
      'wind_speed': realtime_data['wind_speed'],
  }])

  # 4. Inforensi Risiko
  risk_class = model.predict(features)[0]
  probabilities = model.predict_proba(features)[0]

  status_map = {
      0: (
          'AMAN (LOW RISK)',
          '🟢 Kondisi air laut stabil. Operasional intake normal.',
      ),
      1: (
          'WASPADA (MEDIUM RISK)',
          '🟡 Indikasi awal kawanan ubur-ubur. Tingkatkan pengawasan visual'
          ' pada Bar Screen & pantau Beda Tekanan (ΔP).',
      ),
      2: (
          'BAHAYA (HIGH RISK / BLOOMING)',
          '🔴 ANCAMAN BLOOMING UBUR-UBUR TINGGI! Siapkan operasi kontinyu'
          ' Travelling Band Screen (TBS) & siagakan tim lokal.',
      ),
  }

  status_str, reko_str = status_map[risk_class]

  # 5. Output Informasi Monitoring
  print('\n================ HASIL MONITORING REAL-TIME ================')
  print(f"Waktu Eksekusi    : {realtime_data['timestamp']}")
  print(
      f'Target Lokasi     : SWI PLTGU Grati, Pasuruan ({GRATI_LAT},'
      f' {GRATI_LON})'
  )
  print('-----------------------------------------------------------')
  print(f"1. Suhu Laut (SST) : {realtime_data['sst']:.2f} °C")
  print(f"2. Salinitas       : {realtime_data['salinity']:.2f} PSU")
  print(f"3. Kecepatan Arus  : {realtime_data['current_speed']:.2f} m/s")
  print(f"4. Klorofil-a      : {realtime_data['chlorophyll_a']:.2f} mg/m³")
  print(f"5. Kecepatan Angin : {realtime_data['wind_speed']:.2f} knot")
  print('-----------------------------------------------------------')
  print(f'PREDIKSI RISIKO ML : {status_str}')
  print(f'Probabilitas High  : {probabilities[2] * 100:.1f}%')
  print(f'Rekomendasi Aksi   : {reko_str}')
  print('===========================================================')


if __name__ == '__main__':
  run_grati_monitoring_system()